---
- hosts: pi-a
  remote_user: pi
  become: yes
  tasks:
  - name: simulate long running op,allow to run for 45 sec,fire and forget
    command: /bin/sleep 15
    async: 45
    poll: 0
  - name: simulate long running op (15 sec),wait for up to 45 sec,poll every 5 sec 
    command: /bin/sleep 15
    async: 45
    poll: 5
  - name: simulate long running op (65 sec),wait for up to 45 sec,poll every 5 sec 
    command: /bin/sleep 65
    async: 45
    poll: 5

