---
- hosts: openfaas.cn
  tasks:
  - name: yum mariadb for test fire and forget task
    yum: name=mariadb-server state=installed
    async: 1000
    poll: 0
    register: yum_sleeper
  - name: check on fire and forget task 
    async_status: jid={{ yum_sleeper.ansible_job_id }}
    register: job_result
    until: job_result.finished
    retries: 30

