---
- hosts: kcon
  gather_facts: True
  remote_user: root
  tasks:
  - name: download cfssl 
    get_url:
      url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
      dest: /usr/local/bin/cfssl
      mode: 0755
  - name: download cfssljson 
    get_url:
      url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
      dest: /usr/local/bin/cfssljson
      mode: 0755
